version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: hafsa
      POSTGRES_PASSWORD: hafsa123
      POSTGRES_DB: rss
    ports:
      - "5432:5432"
    volumes:
      - my-db:/var/lib/postgresql/data
volumes:
  my-db: